### PR TITLE
Add Laravel 9 support & update to Enhance Resources v4

### PR DESCRIPTION
**Pull request by joeladam518**
- Drops support for PHP 7.4
- Drops support for Laravel 7
- Updates github actions to matrix laravel version in tests

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Can you help talk through the v4 vs the other v4? Is this like a v3 version that dropped supported for older php, thus was a breaking change and needed new version?

**Comment by erik-perri** [comment]
@iBotPeaches That is correct, in order to support Laravel 9 we need to drop support for PHP 7.4.  Since that is a breaking change this update will become 4.x (which should be an easy update for any projects wanting to update to L9 without rebuilding the resources) and the other PR will need to become 5.x instead.

**Comment by iBotPeaches** [comment]
Got it, so lets back rename some of the alpha/devs of the old v4 and repush those tags to reflect v5 then we can go forward with w/ this one.

**Comment by Jasonej** [comment]
@iBotPeaches The v4 releases have been recreated as v5 to make room for this being v4.

**Review by iBotPeaches — APPROVED** [review]

**Review by erik-perri — APPROVED** [review]

**Review by NilsDelaguardia — APPROVED** [review]

**Review by Jasonej — APPROVED** [review]

**Pull request merged**
